name       : python-minimock
version    : 1.2.8
release    : 4
source     :
    - https://pypi.python.org/packages/source/M/MiniMock/MiniMock-1.2.8.tar.gz : 5fdfdfeadf0fc781d0592a1b90d2fcc11581f682ff7cba6201cfdb15c3ea5a4c
license    : MIT
component  : programming.python
summary    : The simplest possible mock library
description: |
    MiniMock is a simple library for doing Mock objects with doctest.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 minimock.py -v
    popd
